# Generated by Django 4.2.30 on 2026-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(max_length=50)),
                ('usu_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('usu_rol', models.CharField(default='cliente', max_length=20)),
                ('usu_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('usu_correo', models.EmailField(max_length=100, unique=True)),
                ('usu_contraseña', models.CharField(max_length=255)),
                ('usu_img', models.ImageField(default='default.png', upload_to='perfiles/')),
            ],
            options={
                'db_table': 'USUARIOS',
            },
        ),
    ]
