# Generated by Django 4.2.30 on 2026-08-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_xiomex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usu_superadmin_original',
            field=models.BooleanField(default=False),
        ),
    ]
