# Generated by Django 4.2.30 on 2026-08-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_xiomex', '0002_usuario_usu_superadmin_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('catg_id', models.AutoField(primary_key=True, serialize=False)),
                ('catg_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIAS',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=100)),
                ('prod_descripcion', models.TextField(blank=True, null=True)),
                ('prod_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_stock', models.PositiveIntegerField(default=0)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('prod_estado', models.CharField(default='activo', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, db_column='catg_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='app_xiomex.categoria')),
            ],
            options={
                'db_table': 'PRODUCTOS',
            },
        ),
    ]
